### ISSUE TITLE
  SyntaxError: import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by touero** [hedgieinsocks/launcher#10]
I download it in github and install by `gnome-extensions install`
  ```
  SyntaxError: import declarations may only appear at top level of a module

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:23:33
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

**Comment by hedgieinsocks** [comment]
Hi, thank you for reporting. I've tried to reproduce it this way:

```bash
❯ gnome-extensions pack
❯ gnome-extensions install launcher@hedgie.tech.shell-extension.zip
# relogin
❯ gnome-extensions enable launcher@hedgie.tech
```
And after that, I could launch my scripts and toggle settings in the preferences menu without facing any errors.

This being said, could you please share more details about your setup, e.g. gnome version and whether the error persists with other extensions disabled?

**Comment by touero** [comment]
OS: Ubuntu 22.04.5 LTS x86_64
Kernel: 6.8.0-49-generic
Packages: 1594 (dpkg), 11 (snap)
DE: GNOME 42.9

**Comment by hedgieinsocks** [comment]
I see, thank you for the details. The project supports only gnome >=45 https://github.com/hedgieinsocks/gnome-extension-launcher/blob/master/metadata.json#L5

The thing is that gnome devs forced ECMAScript modules in gnome 45 release https://gjs.guide/extensions/upgrading/gnome-shell-45.html

So if you do want to try this extension on gnome 42, you can try to use the last commit before gnome 45 port https://github.com/hedgieinsocks/gnome-extension-launcher/tree/8a5dc37228abbb1ac499f855bf69602d00b30044

**Comment by touero** [comment]
Thanks, but I can set the script path after installation, 
and also execute
```shell
 gnome-extensions enable launcher@hedgie.tech
```
But it still cannot be enabled, it is displayed in `gnome-manager`：
![image](https://github.com/user-attachments/assets/c351188f-6147-4d1d-ac7a-a4705819326c)

**Comment by hedgieinsocks** [comment]
I guess to be able to actually enable the extension, you must first add 42 to the list of the supported versions in metadata.json

**Comment by touero** [comment]
Ok it's solved, but I still have questions
Why does it not support previous gnome versions? Because most programs still need to run the old version.
Is it because he has a bug or some other reason?

Thank you again for your patient answer.

**Comment by hedgieinsocks** [comment]
I wrote the extension shortly after I switched from kde to gnome 43. I did not test it on older 40-42 versions, so it officially supported only 43 from the start. Then, when gnome 45 was released and required code refactoring, I've just decided to target only the latest gnome releases to avoid backporting struggle and extra maintainace burden.

**Comment by touero** [comment]
Thank you.
Maybe I will fork it or create a new repo and keep it version gnome 42.
And mark it's upstream is your repo.
Bc I think it is a useful tools for me.
