### ISSUE TITLE
Failed to execute

### ISSUE THREAD

**Issue by Hyphonical** [hedgieinsocks/launcher#8]
Hello, I'm trying to use your Gnome extension, but I've stumbled across an issue with executing the program. It gives me an error that I don't have the right permission to execute that program, even tho it's a pretty simple program. I am not so familiar with your extension, so could you help me get started?

Thanks in advance.
![Untitled](https://github.com/hedgieinsocks/launcher/assets/69310714/4ec22062-acef-40c7-aaaf-bdb892e45325)
![Screenshot from 2023-12-29 22-43-42](https://github.com/hedgieinsocks/launcher/assets/69310714/bf426a86-6b5b-4575-9c33-5a65684ff47c)

**Comment by hedgieinsocks** [comment]
@Hyphonic Hi, most likely you need to set an executive bit via `chmod +x main.sh` or `chmod 744 main.sh`

**Comment by Hyphonical** [comment]
Yes, that's the solution, thanks again. I'm just a beginner when it comes to Linux, as I recently installed it. 😊
